library(tidyverse)
library(lme4)
library(lmerTest)

# =============================================================================
# SENSITIVITY ANALYSIS: within-species variation in brightness
# Tests whether the 14 multi-site species show HSV brightness variation across
# sites consistent with the desiccation hypothesis (darker at drier sites).
#
# Desiccation hypothesis predicts:
#   - Negative correlation between VPD and brightness
#     (drier = higher VPD = darker = lower brightness)
#   - Positive correlation between soil moisture and brightness
#     (wetter = higher moisture = lighter = higher brightness)
# =============================================================================

# --- Helper functions --------------------------------------------------------

strip_subspecies <- function(x) {
  words <- str_split(x, " ")
  map_chr(words, ~ if (length(.x) >= 3) paste(.x[1], .x[2]) else paste(.x, collapse = " "))
}

sign_test <- function(cors, predicted_positive = TRUE) {
  # Exact binomial test: H1 = more species show predicted direction than chance
  cors_clean <- cors[!is.na(cors)]
  n          <- length(cors_clean)
  n_correct  <- if (predicted_positive) sum(cors_clean > 0) else sum(cors_clean < 0)
  binom.test(n_correct, n, p = 0.5, alternative = "greater")
}

# --- Load data ---------------------------------------------------------------

# Unscaled raw data (needed for within-species correlations on original scale)
mdf_raw <- read.csv("data/melanism_modelDF.csv") %>%
  mutate(SpeciesName_match = strip_subspecies(SpeciesName))

# HSV brightness values (generated by HSV sensitivity analysis script)
hsv <- read.csv("data/melanism_HSV.csv")

mdf_raw <- left_join(mdf_raw, hsv)

# --- Identify multi-site species ---------------------------------------------

species_site_counts <- mdf_raw %>%
  group_by(SpeciesName_match) %>%
  summarise(n_sites = n_distinct(IL_Site), .groups = "drop") %>%
  arrange(desc(n_sites))

multi_site_species <- species_site_counts %>%
  filter(n_sites >= 2) %>%
  pull(SpeciesName_match)

cat(sprintf("\n%d species sampled at 2+ sites:\n", length(multi_site_species)))
print(species_site_counts %>% filter(n_sites >= 2))

# --- Compute site-level means per species ------------------------------------

spp_site_means <- mdf_raw %>%
  filter(SpeciesName_match %in% multi_site_species) %>%
  group_by(SpeciesName_match, IL_Site) %>%
  summarise(
    mean_dorsal_brightness  = mean(HSV_V_dorsal,    na.rm = TRUE),
    mean_ventral_brightness = mean(HSV_V_ventral,   na.rm = TRUE),
    mean_VPD                = mean(meanVPD,          na.rm = TRUE),
    mean_soil_moisture      = mean(meanSoilMoisture, na.rm = TRUE),
    n_individuals           = n(),
    .groups = "drop"
  )

# --- Within-species Spearman correlations ------------------------------------

within_species_cors <- spp_site_means %>%
  group_by(SpeciesName_match) %>%
  summarise(
    n_sites         = n(),
    cor_VPD_dorsal  = cor(mean_VPD,          mean_dorsal_brightness,  method = "spearman"),
    cor_VPD_ventral = cor(mean_VPD,          mean_ventral_brightness, method = "spearman"),
    cor_SM_dorsal   = cor(mean_soil_moisture, mean_dorsal_brightness,  method = "spearman"),
    cor_SM_ventral  = cor(mean_soil_moisture, mean_ventral_brightness, method = "spearman"),
    .groups = "drop"
  ) %>%
  arrange(desc(n_sites))

cat("\n--- Within-species correlations (Spearman) ---\n")
cat("Desiccation hypothesis predicts: cor_VPD < 0, cor_SM > 0\n\n")
print(within_species_cors)

# --- Direction summary -------------------------------------------------------

direction_summary <- within_species_cors %>%
  summarise(
    n_species                   = n(),
    pct_VPD_dorsal_correct_dir  = mean(cor_VPD_dorsal  < 0, na.rm = TRUE) * 100,
    pct_VPD_ventral_correct_dir = mean(cor_VPD_ventral < 0, na.rm = TRUE) * 100,
    pct_SM_dorsal_correct_dir   = mean(cor_SM_dorsal   > 0, na.rm = TRUE) * 100,
    pct_SM_ventral_correct_dir  = mean(cor_SM_ventral  > 0, na.rm = TRUE) * 100,
    median_cor_VPD_dorsal       = median(cor_VPD_dorsal,  na.rm = TRUE),
    median_cor_VPD_ventral      = median(cor_VPD_ventral, na.rm = TRUE),
    median_cor_SM_dorsal        = median(cor_SM_dorsal,   na.rm = TRUE),
    median_cor_SM_ventral       = median(cor_SM_ventral,  na.rm = TRUE)
  )

cat("\n--- Direction summary ---\n")
print(direction_summary)

# --- Sign tests --------------------------------------------------------------

cat("\n--- Sign tests (binomial, H1: more species show predicted direction than chance) ---\n")

cat("\nVPD ~ dorsal brightness (predicted negative):\n")
print(sign_test(within_species_cors$cor_VPD_dorsal, predicted_positive = FALSE))

cat("VPD ~ ventral brightness (predicted negative):\n")
print(sign_test(within_species_cors$cor_VPD_ventral, predicted_positive = FALSE))

cat("Soil moisture ~ dorsal brightness (predicted positive):\n")
print(sign_test(within_species_cors$cor_SM_dorsal, predicted_positive = TRUE))

cat("Soil moisture ~ ventral brightness (predicted positive):\n")
print(sign_test(within_species_cors$cor_SM_ventral, predicted_positive = TRUE))

# --- Figure ------------------------------------------------------------------

cors_long <- within_species_cors %>%
  select(SpeciesName_match, n_sites,
         `VPD ~ dorsal`       = cor_VPD_dorsal,
         `VPD ~ ventral`      = cor_VPD_ventral,
         `Moisture ~ dorsal`  = cor_SM_dorsal,
         `Moisture ~ ventral` = cor_SM_ventral) %>%
  pivot_longer(-c(SpeciesName_match, n_sites),
               names_to  = "comparison",
               values_to = "correlation") %>%
  mutate(
    predicted_direction = if_else(str_detect(comparison, "VPD"), "negative", "positive"),
    consistent = case_when(
      predicted_direction == "negative" & correlation < 0 ~ "Consistent",
      predicted_direction == "positive" & correlation > 0 ~ "Consistent",
      TRUE                                                 ~ "Inconsistent"
    ),
    SpeciesName_match = fct_reorder(SpeciesName_match, n_sites)
  )

p_within_cors <- ggplot(cors_long,
                        aes(x = correlation, y = SpeciesName_match,
                            color = consistent, shape = consistent)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey50") +
  geom_point(size = 2.5) +
  scale_color_manual(values = c("Consistent"   = "#2c7bb6",
                                "Inconsistent" = "#d7191c")) +
  scale_shape_manual(values = c("Consistent" = 16, "Inconsistent" = 1)) +
  facet_wrap(~ comparison, nrow = 2) +
  labs(x = "Spearman correlation", y = "",
       color = "Direction", shape = "Direction") +
  theme_classic() +
  theme(axis.text.y     = element_text(size = 9, face = "italic"),
        axis.text.x     = element_text(size = 10),
        strip.text      = element_text(size = 11),
        legend.position = "bottom")

ggsave("figureOutputs/within_species_sensitivity.png",
       p_within_cors, dpi = 550, width = 9, height = 7)

cat("\nFigure saved to figureOutputs/within_species_sensitivity.png\n")

# --- Save supplement table ---------------------------------------------------

write_csv(within_species_cors,
          "modelResults/within_species_correlations_supplement.csv")

cat("Supplement table saved to modelResults/within_species_correlations_supplement.csv\n")
